### ISSUE TITLE
main.rkt not found when requiring data

### ISSUE THREAD

**Issue by benkwokcy** [racket/data#20]
I am using DrRacket, version 8.0 [cs].

When running the following code:
```
#lang racket
(require data)
```

I get the following error: 

```
open-input-file: cannot open module file module path: data path: /Applications/Racket v8.0/collects/data/main.rkt system error: no such file or directory; rkt_err=3
```

```
. . ../../../../Applications/Racket v8.0/share/pkgs/gui-lib/mred/private/snipfile.rkt:324:2: open-input-file: cannot open module file
  module path: data
  path: /Applications/Racket v8.0/collects/data/main.rkt
  system error: no such file or directory; rkt_err=3
  packages that provide the missing module: [update catalog]
    set  [install]
```

**Comment by jbclements** [comment]
Right, I believe that's by design. There's no top-level "require everything" for data. I believe that if you take a look at the docs for the data collection, you'll see that the data collection is actually a grouping of a whole bunch of different data structures, and it's unlikely that you'd want to import them all. If you take a look at the docs for a particular data structure, say, Interval Maps (https://docs.racket-lang.org/data/interval-map.html?q=data), you'll see that you'd import that using
```
(require data/interval-map)
```
Does this make sense?

**Comment by benkwokcy** [comment]
Thanks for clarifying. I think you're probably right that I'll just need 1-2 of the data structures at a time. I think what confused me is that it says "(require data)" at the top of the main page of the docs (https://docs.racket-lang.org/data/index.html?q=data).

**Comment by jbclements** [comment]
Well, that's actually a really good point; it probably shouldn't say "(require data)" at the top of the docs...

**Comment by jbclements** [comment]
@samth I just took a look at the scribble for the data module, and I'm wondering if it would be safe to just delete the "@defmodule[data]" at the top, to eliminate the bogus (require data) that's generated in the docs? I'm picking on you because you committed this file, lo these eleven years ago....

**Comment by samth** [comment]
That's definitely the right fix.
